// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tinysocialnetwork.proto
#ifndef GRPC_tinysocialnetwork_2eproto__INCLUDED
#define GRPC_tinysocialnetwork_2eproto__INCLUDED

#include "tinysocialnetwork.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tinysocialnetwork {

// The Social Network Service
class SNetwork final {
 public:
  static constexpr char const* service_full_name() {
    return "tinysocialnetwork.SNetwork";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status create_user(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::tinysocialnetwork::CreateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::CreateReply>> Asynccreate_user(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::CreateReply>>(Asynccreate_userRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::CreateReply>> PrepareAsynccreate_user(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::CreateReply>>(PrepareAsynccreate_userRaw(context, request, cq));
    }
    virtual ::grpc::Status follow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::tinysocialnetwork::UserReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>> Asyncfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>>(AsyncfollowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>> PrepareAsyncfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>>(PrepareAsyncfollowRaw(context, request, cq));
    }
    virtual ::grpc::Status unfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::tinysocialnetwork::UserReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>> Asyncunfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>>(AsyncunfollowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>> PrepareAsyncunfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>>(PrepareAsyncunfollowRaw(context, request, cq));
    }
    virtual ::grpc::Status list(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::tinysocialnetwork::ListReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::ListReply>> Asynclist(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::ListReply>>(AsynclistRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::ListReply>> PrepareAsynclist(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::ListReply>>(PrepareAsynclistRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>> timeline(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>>(timelineRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>> Asynctimeline(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>>(AsynctimelineRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>> PrepareAsynctimeline(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>>(PrepareAsynctimelineRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::CreateReply>* Asynccreate_userRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::CreateReply>* PrepareAsynccreate_userRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>* AsyncfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>* PrepareAsyncfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>* AsyncunfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::UserReply>* PrepareAsyncunfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::ListReply>* AsynclistRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tinysocialnetwork::ListReply>* PrepareAsynclistRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* timelineRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* AsynctimelineRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* PrepareAsynctimelineRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status create_user(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::tinysocialnetwork::CreateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::CreateReply>> Asynccreate_user(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::CreateReply>>(Asynccreate_userRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::CreateReply>> PrepareAsynccreate_user(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::CreateReply>>(PrepareAsynccreate_userRaw(context, request, cq));
    }
    ::grpc::Status follow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::tinysocialnetwork::UserReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>> Asyncfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>>(AsyncfollowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>> PrepareAsyncfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>>(PrepareAsyncfollowRaw(context, request, cq));
    }
    ::grpc::Status unfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::tinysocialnetwork::UserReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>> Asyncunfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>>(AsyncunfollowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>> PrepareAsyncunfollow(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>>(PrepareAsyncunfollowRaw(context, request, cq));
    }
    ::grpc::Status list(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::tinysocialnetwork::ListReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::ListReply>> Asynclist(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::ListReply>>(AsynclistRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::ListReply>> PrepareAsynclist(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::ListReply>>(PrepareAsynclistRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>> timeline(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>>(timelineRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>> Asynctimeline(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>>(AsynctimelineRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>> PrepareAsynctimeline(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>>(PrepareAsynctimelineRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::CreateReply>* Asynccreate_userRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::CreateReply>* PrepareAsynccreate_userRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::CreateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>* AsyncfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>* PrepareAsyncfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>* AsyncunfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::UserReply>* PrepareAsyncunfollowRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::ListReply>* AsynclistRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tinysocialnetwork::ListReply>* PrepareAsynclistRaw(::grpc::ClientContext* context, const ::tinysocialnetwork::ListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* timelineRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* AsynctimelineRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* PrepareAsynctimelineRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_create_user_;
    const ::grpc::internal::RpcMethod rpcmethod_follow_;
    const ::grpc::internal::RpcMethod rpcmethod_unfollow_;
    const ::grpc::internal::RpcMethod rpcmethod_list_;
    const ::grpc::internal::RpcMethod rpcmethod_timeline_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status create_user(::grpc::ServerContext* context, const ::tinysocialnetwork::CreateRequest* request, ::tinysocialnetwork::CreateReply* response);
    virtual ::grpc::Status follow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response);
    virtual ::grpc::Status unfollow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response);
    virtual ::grpc::Status list(::grpc::ServerContext* context, const ::tinysocialnetwork::ListRequest* request, ::tinysocialnetwork::ListReply* response);
    virtual ::grpc::Status timeline(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_create_user : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_create_user() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_create_user() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status create_user(::grpc::ServerContext* context, const ::tinysocialnetwork::CreateRequest* request, ::tinysocialnetwork::CreateReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcreate_user(::grpc::ServerContext* context, ::tinysocialnetwork::CreateRequest* request, ::grpc::ServerAsyncResponseWriter< ::tinysocialnetwork::CreateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_follow() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfollow(::grpc::ServerContext* context, ::tinysocialnetwork::UserRequest* request, ::grpc::ServerAsyncResponseWriter< ::tinysocialnetwork::UserReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_unfollow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_unfollow() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_unfollow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unfollow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestunfollow(::grpc::ServerContext* context, ::tinysocialnetwork::UserRequest* request, ::grpc::ServerAsyncResponseWriter< ::tinysocialnetwork::UserReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_list() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status list(::grpc::ServerContext* context, const ::tinysocialnetwork::ListRequest* request, ::tinysocialnetwork::ListReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestlist(::grpc::ServerContext* context, ::tinysocialnetwork::ListRequest* request, ::grpc::ServerAsyncResponseWriter< ::tinysocialnetwork::ListReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_timeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_timeline() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_timeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status timeline(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesttimeline(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(4, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_create_user<WithAsyncMethod_follow<WithAsyncMethod_unfollow<WithAsyncMethod_list<WithAsyncMethod_timeline<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_create_user : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_create_user() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_create_user() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status create_user(::grpc::ServerContext* context, const ::tinysocialnetwork::CreateRequest* request, ::tinysocialnetwork::CreateReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_follow() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_unfollow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_unfollow() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_unfollow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unfollow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_list() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status list(::grpc::ServerContext* context, const ::tinysocialnetwork::ListRequest* request, ::tinysocialnetwork::ListReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_timeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_timeline() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_timeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status timeline(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::tinysocialnetwork::TimelineStream, ::tinysocialnetwork::TimelineStream>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_create_user : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_create_user() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::tinysocialnetwork::CreateRequest, ::tinysocialnetwork::CreateReply>(std::bind(&WithStreamedUnaryMethod_create_user<BaseClass>::Streamedcreate_user, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_create_user() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status create_user(::grpc::ServerContext* context, const ::tinysocialnetwork::CreateRequest* request, ::tinysocialnetwork::CreateReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcreate_user(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tinysocialnetwork::CreateRequest,::tinysocialnetwork::CreateReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_follow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_follow() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::tinysocialnetwork::UserRequest, ::tinysocialnetwork::UserReply>(std::bind(&WithStreamedUnaryMethod_follow<BaseClass>::Streamedfollow, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_follow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status follow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedfollow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tinysocialnetwork::UserRequest,::tinysocialnetwork::UserReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_unfollow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_unfollow() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::tinysocialnetwork::UserRequest, ::tinysocialnetwork::UserReply>(std::bind(&WithStreamedUnaryMethod_unfollow<BaseClass>::Streamedunfollow, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_unfollow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status unfollow(::grpc::ServerContext* context, const ::tinysocialnetwork::UserRequest* request, ::tinysocialnetwork::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedunfollow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tinysocialnetwork::UserRequest,::tinysocialnetwork::UserReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_list : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_list() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::tinysocialnetwork::ListRequest, ::tinysocialnetwork::ListReply>(std::bind(&WithStreamedUnaryMethod_list<BaseClass>::Streamedlist, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_list() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status list(::grpc::ServerContext* context, const ::tinysocialnetwork::ListRequest* request, ::tinysocialnetwork::ListReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedlist(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tinysocialnetwork::ListRequest,::tinysocialnetwork::ListReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_create_user<WithStreamedUnaryMethod_follow<WithStreamedUnaryMethod_unfollow<WithStreamedUnaryMethod_list<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_create_user<WithStreamedUnaryMethod_follow<WithStreamedUnaryMethod_unfollow<WithStreamedUnaryMethod_list<Service > > > > StreamedService;
};

}  // namespace tinysocialnetwork


#endif  // GRPC_tinysocialnetwork_2eproto__INCLUDED
